### PR TITLE
Add Caesar cipher program

### PR DESCRIPTION
**Pull request by prathimacode-hub**
Added Caesar cipher program

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Hey @prathimacode-hub!

Thanks for your contributions! This is a nice thing to add. I have optimised your code a bit. You can check the [commits](https://github.com/aravindvnair99/Python/pull/18/commits) for what I did.

I did notice your code doesn't validate the input. Could you fix that? Once you are done, I shall merge this PR. To give you more context:

```console
$ python3 CaesarCipher.py

Pick one of the options:

1.Encrypt
2.Decrypt
0.Exit

typing some words here instead of actual number as input
Traceback (most recent call last):
  File "CaesarCipher.py", line 59, in <module>
    opt = int(input("\nPick one of the options:\n\n1.Encrypt\n2.Decrypt\n0.Exit\n\n"))
ValueError: invalid literal for int() with base 10: 'typing some words here instead of actual number as input'
```

This is just one example. The same applies to other inputs as well. Let me know if you didn't understand and I can explain more.

**Comment by prathimacode-hub** [comment]
Yes, Can you elaborate it further? @aravindvnair99

**Comment by aravindvnair99** [comment]
> Yes, Can you elaborate it further? @aravindvnair99

Sure @prathimacode-hub, input validation is the process of verifying the input is indeed what we are expecting and not anything else. This not only prevents unexpected errors but, in most cases (big production-level applications), also prevent security risks. It's always necessary to validate user input than accept it simply and this also is a safer way to code.

For example, in my [previous message](https://github.com/aravindvnair99/Python/pull/18#pullrequestreview-664570448), you can see I gave the input as letters instead of the number and the program crashed instead of asking me to enter again. If input validation was instead implemented, what would have happened is that it would have checked to ensure it is indeed a number before proceeding further and if not asking the user to enter again.

Similarly, for other inputs as well, proper validation should be done. I would suggest you give these 2 a read:

- [Python input validation best practices](https://www.google.com/search?q=python+input+validation+best+practices)
- [Python input validation](https://www.google.com/search?q=python+input+validation)

Once you have understood why we need to do this and how to do it, you can try implementing the same and I will review your code again. Also, if you are editing in your browser, you can edit directly as you will always have the latest commits. But if instead, you are editing locally on your system, make sure to pull the commits before starting to edit so that you have the latest code. Feel free to keep pushing commits or tag me anytime.

**Comment by aravindvnair99** [comment]
Hey @prathimacode-hub!

I just wanted to follow up with you as I got no response back. Were you able to understand what I was saying? Would you be fixing it?

**Comment by prathimacode-hub** [comment]
Yes, got you. Thanks for asking. I will fix it soon. Got held up with other things. @aravindvnair99

**Comment by aravindvnair99** [comment]
> Yes, got you. Thanks for asking. I will fix it soon. Got held up with other things. @aravindvnair99

Great! Thanks for confirming @prathimacode-hub! Looking forward to your fix. Let me know if you need any assistance.

**Comment by aravindvnair99** [comment]
Hey @prathimacode-hub!

I just wanted to follow up with you. Were you able to fix it? Are you still working on it?

**Comment by aravindvnair99** [comment]
Hey @prathimacode-hub!

I just wanted to follow up with you as it's been 2 weeks. Were you able to fix it? Are you still working on it?

**Comment by aravindvnair99** [comment]
Hey @prathimacode-hub!

I just wanted to follow up with you as it's been a month. Were you able to fix it? Are you still working on it?

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Hey @prathimacode-hub!

I just wanted to follow up with you as it's been a few months. Were you able to fix it? Are you still working on it?

**Comment by prathimacode-hub** [comment]
Hey sorry got busy with other things, I will do it in 4-5 days. Sure. @aravindvnair99

**Pull request closed without merging**
